/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package linketinder.projeto.gradle

import linketinder.projeto.gradle.DAO.CurtidasCandidatoDAO
import linketinder.projeto.gradle.DAO.CurtidasEmpresaDAO
import linketinder.projeto.gradle.UI.CandidatoUI
import linketinder.projeto.gradle.UI.CompetenciaUI
import linketinder.projeto.gradle.UI.EmpresaUI
import linketinder.projeto.gradle.UI.MatchUI
import linketinder.projeto.gradle.UI.VagaUI
import linketinder.projeto.gradle.Utils.Menu

// SOPHIA SOUSA-AGUIAR LUNA
class App{
    static void main(String[] args) {

        boolean loop=true
        while(loop){

            Menu.displayMenu()
            int i = System.in.newReader().readLine() as Integer

            switch (i) {
                case 1:

                    CandidatoUI.criar()
                    break

                case 2:

                    CandidatoUI.alterar()
                    break

                case 3:

                    CandidatoUI.deletar()
                    break

                case 4:

                    CandidatoUI.listar()
                    break

                case 5:

                    EmpresaUI.criar()
                    break

                case 6:

                    EmpresaUI.alterar()
                    break

                case 7:

                    EmpresaUI.deletar()
                    break

                case 8:

                    EmpresaUI.listar()
                    break

                case 9:

                    VagaUI.criar()
                    break

                case 10:

                    VagaUI.alterar()
                    break

                case 11:

                    VagaUI.deletar()
                    break

                case 12:

                    VagaUI.listar()
                    break

                case 13:

                    CompetenciaUI.cadastrar()
                    break

                case 14:

                    CompetenciaUI.cadastrarCompetenciaCandidato()
                    break

                case 15:

                    CompetenciaUI.cadastrarCompetenciaVaga()
                    break

                case 16:

                    CompetenciaUI.deletar()
                    break

                case 17:

                    println("Insira o CNPJ da empresa: ")
                    String cnpj=System.in.newReader().readLine()

                    println("Insira o CPF do candidato: ")
                    String cpf=System.in.newReader().readLine()

                    CurtidasEmpresaDAO.curtir(cnpj, cpf)
                    break

                case 18:

                    println("Insira o CPF do candidato: ")
                    String cpf=System.in.newReader().readLine()

                    println("Insira o ID da vaga: ")
                    String id=System.in.newReader().readLine()

                    CurtidasCandidatoDAO.curtir(cpf, id)
                    break

                case 19:

                    MatchUI.listar()
                    break

                case 20:

                    loop=false
                    break

                default:

                    println("Opção Inválida.")
                    break

            }
        }
    }

}


