/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package linketinder.projeto.gradle

import linketinder.projeto.gradle.Utils.Menu
import linketinder.projeto.gradle.View.CandidatoView
import linketinder.projeto.gradle.View.CompetenciaView
import linketinder.projeto.gradle.View.CurtidasView
import linketinder.projeto.gradle.View.EmpresaView
import linketinder.projeto.gradle.View.MatchView
import linketinder.projeto.gradle.View.VagaView

// SOPHIA SOUSA-AGUIAR LUNA
class App{
    static void main(String[] args) {

        println("Bem Vindo(a) ao Linketinder!")

        boolean loop=true
        while(loop){

            Menu.displayMenu()
            int i = System.in.newReader().readLine() as Integer

            switch (i) {
                case 1:

                    CandidatoView.criar()
                    break

                case 2:

                    CandidatoView.alterar()
                    break

                case 3:

                    CandidatoView.deletar()
                    break

                case 4:

                    CandidatoView.listar()
                    break

                case 5:

                    EmpresaView.criar()
                    break

                case 6:

                    EmpresaView.alterar()
                    break

                case 7:

                    EmpresaView.deletar()
                    break

                case 8:

                    EmpresaView.listar()
                    break

                case 9:

                    VagaView.criar()
                    break

                case 10:

                    VagaView.alterar()
                    break

                case 11:

                    VagaView.deletar()
                    break

                case 12:

                    VagaView.listar()
                    break

                case 13:

                    CompetenciaView.cadastrar()
                    break

                case 14:

                    CompetenciaView.cadastrarCompetenciaCandidato()
                    break

                case 15:

                    CompetenciaView.cadastrarCompetenciaVaga()
                    break

                case 16:

                    CompetenciaView.deletar()
                    break

                case 17:

                    CurtidasView.curtidasEmpresa()
                    break

                case 18:

                    CurtidasView.curtidasCandidato()
                    break

                case 19:

                    MatchView.listar()
                    break

                case 20:

                    loop=false
                    break

                default:

                    println("Opção Inválida.")
                    break

            }
        }
    }

}


